### ISSUE TITLE
:trollface: 

### ISSUE THREAD

**Issue by Samyocord** [Fisch03/Hanako-Discord#59]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when 
:trollface: 

**Describe the solution you'd like**
:trollface: 

**Describe alternatives you've considered**

:trollface: 

**Additional context**
:trollface: 

no way github has trollface

**Comment by Samyocord** [comment]
github has trollface :trollface:

**Comment by Fisch03** [comment]
:trollface:
